### ISSUE TITLE
Add support for Laravel 10.

### ISSUE THREAD

**Issue by JessengBijleng** [t1nkl/postgres-pgbouncer-extension#1]
Hi,

Since Laravel 10 has been released, it would be great if this package would support it. Currently `composer install` is throwing this error:

`t1nkl/postgres-pgbouncer-extension[1.0.0, ..., 1.0.1] require laravel/framework ^7.0|^8.0|^9.0 -> found laravel/framework[v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.0] but it conflicts with your root composer.json require (^10.0).`

Guessing it as simple as adding `|^10.0` to the src composer.json

ps; seeing you're from UR, hoping you are safe. (Y)

**Comment by t1nkl** [comment]
@JessengBijleng Hello.
I'm sorry it took so long before I answered you.
I added laravel 10 support in composer.json file
